(function(d){d.popover=function(f,e,g){var b=this;b.$el=d(f);b.el=f;b.$el.data("popover",b);b.init=function(){b.options=d.extend({},d.popover.defaultOptions,g);d(e).appendTo(d("body")).prepend('<div class="triangle"></div>');b.options.triangle$=d(".triangle",d(e));d.fn.popover.openedPopup=null;d(document).unbind(".popover");d(document).bind("click.popover",function(b){d(b.target).parents(".popover").length==0&&!d(b.target).data("popover")&&d.popover.close()});b.options.closeOnEsc&&d(document).bind("keydown",
function(c){!c.altKey&&!c.ctrlKey&&!c.shiftKey&&c.keyCode==27&&b.$el.trigger("close.popover")});b.$el.live("click",function(c){b.toggle(d(c.target));return false});b.$el.live("open.popover",function(c){b.open(d(c.target));return false});b.$el.live("close.popover",function(c){b.close(d(c.target));return false});return b.$el};b.calcPopoverDirPossible=function(c,a){var d={left:false,right:false,top:false,bottom:false};if(c.offset().top+a.buttonHeight+a.triangleSize+a.popoverHeight<=a.docHeight-b.options.padding)d.bottom=
true;if(c.offset().top-a.triangleSize-a.popoverHeight>=b.options.padding)d.top=true;if(c.offset().left+a.buttonWidth+a.triangleSize+a.popoverWidth<=a.docWidth-b.options.padding)d.right=true;if(c.offset().left-a.triangleSize-a.popoverWidth>=b.options.padding)d.left=true;return d};b.chooseDir=function(c){if(b.options.preventBottom)c.bottom=false;if(b.options.preventTop)c.top=false;if(b.options.preventLeft)c.left=false;if(b.options.preventRight)c.right=false;var a="right";b.options.preventRight&&(a=
"bottom");b.options.preventBottom&&(a="top");b.options.preventTop&&(a="left");c.right?a="right":c.bottom?a="bottom":c.left?a="left":c.top&&(a="top");return a};b.calcPopoverPos=function(c){d(e).css("display","block");var a={popoverDir:"bottom",left:c.offset().left,top:c.offset().top,offset:[0,0],triangleX:0,triangleY:0,triangleSize:20,docWidth:d(window).width(),docHeight:d(window).height(),popoverWidth:d(e).outerWidth(),popoverHeight:d(e).outerHeight(),buttonWidth:c.outerWidth(),buttonHeight:c.outerHeight()},
c=b.calcPopoverDirPossible(c,a);a.popoverDir=b.chooseDir(c);a.popoverDir=="bottom"?a.top+=a.buttonHeight+a.triangleSize:a.popoverDir=="top"?a.top-=a.triangleSize+a.popoverHeight:a.top+=(a.buttonHeight-a.popoverHeight)/2;a.popoverDir=="bottom"||a.popoverDir=="top"?(a.left+=(a.buttonWidth-a.popoverWidth)/2,a.left<b.options.padding?a.offset[0]=a.left-b.options.padding:a.left+a.popoverWidth>a.docWidth-b.options.padding&&(a.offset[0]=a.left+a.popoverWidth-a.docWidth+b.options.padding),a.triangleX=a.popoverWidth/
2-a.triangleSize+a.offset[0],a.triangleY=0):(a.popoverDir=="right"?a.left+=a.buttonWidth+a.triangleSize:a.left-=a.triangleSize+a.popoverWidth,a.top<b.options.padding?a.offset[1]=a.top-b.options.padding:a.top+a.popoverHeight>a.docHeight-b.options.padding&&(a.offset[1]=a.top+a.popoverHeight-a.docHeight+b.options.padding),a.triangleX=0,a.triangleY=a.popoverHeight/2-a.triangleSize+a.offset[1]);return a};b.positionPopover=function(c){b.options.triangle$.removeClass("left top right bottom");b.options.triangle$.addClass(c.popoverDir);
c.triangleX>0&&b.options.triangle$.css("left",c.triangleX);c.triangleY>0&&b.options.triangle$.css("top",c.triangleY);d(e).offset({top:c.top-c.offset[1]+b.options.offset[1],left:c.left-c.offset[0]+b.options.offset[0]});d(e).show()};b.toggle=function(c,a){d.fn.popover.openedPopup&&d.fn.popover.openedPopup.get(0)===c.get(0)?a||d.popover.close():b.open(c)};b.open=function(c){d.popover.close();b.options.triangle$.attr("style","");b.positionPopover(b.calcPopoverPos(c));setTimeout(function(){d(e).addClass("active")},
0);d.fn.popover.openedPopup=c;b.options.onOpen(c)};b.close=function(c){d(e).removeClass("active").attr("style","").hide();d.fn.popover.openedPopup=null;b.options.onClose(c)};b.getTrigger=function(){return b.$el};b.getPopover=function(){return d(e)};b.init()};d.popover.close=function(){d.fn.popover.openedPopup!=null&&d.fn.popover.openedPopup.trigger("close.popover")};d.popover.defaultOptions={offset:[0,0],padding:18,closeOnEsc:true,preventLeft:false,preventRight:false,preventTop:false,preventBottom:false,
onOpen:function(){},onClose:function(){}};d.fn.popover=function(f,e){return this.each(function(){new d.popover(this,f,e)})}})(jQuery);
